title: objectbased | Engineering
author: objectbased
#description: Software development and automation with a focus on Security

theme_config:
  show_projects: true
  home:
    title_projects: Projects
    title_skill: Technologies
    